### ISSUE TITLE
No Download button

### ISSUE THREAD

**Issue by abdujack** [skyguy126/Xposed-SoundCloudDownloader#14]
Hi bro first i need to say tanx for making this nice xposed module.. but the new update is not work
I uninstalled the old version before i install the new but it's not work..
Can u help me plz !

**Comment by gdimakis** [comment]
Indeed after the last soundcloud update the download option is not available.

**Comment by abdujack** [comment]
So what !

**Comment by skyguy126** [comment]
Have you tried a full reboot (not soft reboot). Refer to #13. If that doesn't work please post your Xposed log here.

**Comment by abdujack** [comment]
Yes i tried


java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.TypedArray to class android.content.res.XResources$XTypedArray
	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:773)
	at de.robv.android.xposed.XposedBridge.access$6(XposedBridge.java:759)
	at de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:358)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.content.res.TypedArray.<init>(Native Method)
	at android.content.res.Resources.getCachedStyledAttributes(Resources.java:3790)
	at android.content.res.Resources.access$400(Resources.java:109)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java:2486)
	at android.content.Context.obtainStyledAttributes(Context.java:415)
	at com.android.server.AttributeCache.get(AttributeCache.java:132)
	at com.android.server.am.ActivityRecord.<init>(ActivityRecord.java:498)
	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2007)
	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1242)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4131)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(Native Method)
	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3978)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at com.android.server.am.ActivityManagerService.startActivity(Native Method)
	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:165)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2715)
	at android.os.Binder.execTransact(Binder.java:404)
	at dalvik.system.NativeStart.run(Native Method)
java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.TypedArray to class android.content.res.XResources$XTypedArray
	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:773)
	at de.robv.android.xposed.XposedBridge.access$6(XposedBridge.java:759)
	at de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:358)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.content.res.TypedArray.<init>(Native Method)
	at android.content.res.Resources.getCachedStyledAttributes(Resources.java:3790)
	at android.content.res.Resources.access$400(Resources.java:109)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java:2456)
	at android.content.Context.obtainStyledAttributes(Context.java:403)
	at android.view.Window.getWindowStyle(Window.java:423)
	at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:2324)
	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:9137)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.TypedArray to class android.content.res.XResources$XTypedArray
	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:773)
	at de.robv.android.xposed.XposedBridge.access$6(XposedBridge.java:759)
	at de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:358)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.content.res.TypedArray.<init>(Native Method)
	at android.content.res.Resources.getCachedStyledAttributes(Resources.java:3790)
	at android.content.res.Resources.access$400(Resources.java:109)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java:2571)
	at android.content.Context.obtainStyledAttributes(Context.java:439)
	at android.view.View.<init>(View.java:3538)
	at android.view.ViewGroup.<init>(ViewGroup.java:470)
	at android.widget.LinearLayout.<init>(LinearLayout.java:177)
	at android.widget.LinearLayout.<init>(LinearLayout.java:173)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:601)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:676)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:701)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3170)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3241)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1821)
	at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:2380)
	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:9137)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)
[SoundCloud Downloader] Module entry, version 1.5.1
[SoundCloud Downloader] Error: java.lang.ClassNotFoundException: avf
fsbi >> dual >> SignalClusterView

mNC                   : Some(com.android.systemui.statusbar.policy.NetworkController_dual@42947c08)

mWifiVisible          : Some(true)

mWifiStrengthId       : Some(id: 2130837963 name: stat_sys_wifi_signal_2)

mMobileVisible        : Some(true)

mMobileVisible2       : Some(false)

mMobileStrengthId1    : Some(id: 2130837914 name: stat_sys_signal_4)

mMobileStrengthId2    : Some(unknown id: 0)

mMobileActivityId1    : Some(unknown id: 0)

mMobileActivityId2    : Some(unknown id: 0)

mMobileTypeId1        : Some(unknown id: 0)

mMobileTypeId2        : Some(unknown id: 0)

mIsAirplaneMode       : Some(false)

mAirplaneIconId       : Some(unknown id: 0)

mHasService           : Some(false)

mSimIconVisible       : Some(true)

mSimIconId            : Some(id: 2130837705 name: stat_sim_gsm_1)

mMobileRoamingId      : Some(unknown id: 0)

mMobileRoamingId2     : Some(unknown id: 0)

mMobileRssiId         : Some(unknown id: 0)

mMobileRssiId2        : Some(unknown id: 0)

mMobileDataState      : Some(-1)

mMobileDataState2     : Some(0)

fsbi >> dual >> data vis: Some(true) | Some(false) lvl: Some(Some(100)) | Some(None) tpe: Some(None) | Some(None)
fsbi >> dual >> SignalClusterView

mNC                   : Some(com.android.systemui.statusbar.policy.NetworkController_dual@42947c08)

mWifiVisible          : Some(true)

mWifiStrengthId       : Some(id: 2130837963 name: stat_sys_wifi_signal_2)

mMobileVisible        : Some(true)

mMobileVisible2       : Some(false)

mMobileStrengthId1    : Some(id: 2130837914 name: stat_sys_signal_4)

mMobileStrengthId2    : Some(unknown id: 0)

mMobileActivityId1    : Some(unknown id: 0)

mMobileActivityId2    : Some(unknown id: 0)

mMobileTypeId1        : Some(unknown id: 0)

mMobileTypeId2        : Some(unknown id: 0)

mIsAirplaneMode       : Some(false)

mAirplaneIconId       : Some(unknown id: 0)

mHasService           : Some(false)

mSimIconVisible       : Some(true)

mSimIconId            : Some(id: 2130837705 name: stat_sim_gsm_1)

mMobileRoamingId      : Some(unknown id: 0)

mMobileRoamingId2     : Some(unknown id: 0)

mMobileRssiId         : Some(unknown id: 0)

mMobileRssiId2        : Some(unknown id: 0)

mMobileDataState      : Some(-1)

mMobileDataState2     : Some(0)

fsbi >> dual >> data vis: Some(true) | Some(false) lvl: Some(Some(100)) | Some(None) tpe: Some(None) | Some(None)
fsbi >> dual >> SignalClusterView

mNC                   : Some(com.android.systemui.statusbar.policy.NetworkController_dual@42947c08)

mWifiVisible          : Some(true)

mWifiStrengthId       : Some(id: 2130837963 name: stat_sys_wifi_signal_2)

mMobileVisible        : Some(true)

mMobileVisible2       : Some(false)

mMobileStrengthId1    : Some(id: 2130837914 name: stat_sys_signal_4)

mMobileStrengthId2    : Some(unknown id: 0)

mMobileActivityId1    : Some(unknown id: 0)

mMobileActivityId2    : Some(unknown id: 0)

mMobileTypeId1        : Some(unknown id: 0)

mMobileTypeId2        : Some(unknown id: 0)

mIsAirplaneMode       : Some(false)

mAirplaneIconId       : Some(unknown id: 0)

mHasService           : Some(false)

mSimIconVisible       : Some(true)

mSimIconId            : Some(id: 2130837705 name: stat_sim_gsm_1)

mMobileRoamingId      : Some(unknown id: 0)

mMobileRoamingId2     : Some(unknown id: 0)

mMobileRssiId         : Some(unknown id: 0)

mMobileRssiId2        : Some(unknown id: 0)

mMobileDataState      : Some(-1)

mMobileDataState2     : Some(0)

fsbi >> dual >> data vis: Some(true) | Some(false) lvl: Some(Some(100)) | Some(None) tpe: Some(None) | Some(None)
fsbi >> dual >> SignalClusterView

mNC                   : Some(com.android.systemui.statusbar.policy.NetworkController_dual@42947c08)

mWifiVisible          : Some(true)

mWifiStrengthId       : Some(id: 2130837963 name: stat_sys_wifi_signal_2)

mMobileVisible        : Some(true)

mMobileVisible2       : Some(false)

mMobileStrengthId1    : Some(id: 2130837914 name: stat_sys_signal_4)

mMobileStrengthId2    : Some(unknown id: 0)

mMobileActivityId1    : Some(unknown id: 0)

mMobileActivityId2    : Some(unknown id: 0)

mMobileTypeId1        : Some(unknown id: 0)

mMobileTypeId2        : Some(unknown id: 0)

mIsAirplaneMode       : Some(false)

mAirplaneIconId       : Some(unknown id: 0)

mHasService           : Some(false)

mSimIconVisible       : Some(true)

mSimIconId            : Some(id: 2130837705 name: stat_sim_gsm_1)

mMobileRoamingId      : Some(unknown id: 0)

mMobileRoamingId2     : Some(unknown id: 0)

mMobileRssiId         : Some(unknown id: 0)

mMobileRssiId2        : Some(unknown id: 0)

mMobileDataState      : Some(-1)

mMobileDataState2     : Some(0)

fsbi >> dual >> data vis: Some(true) | Some(false) lvl: Some(Some(100)) | Some(None) tpe: Some(None) | Some(None)
fsbi >> dual >> SignalClusterView

mNC                   : Some(com.android.systemui.statusbar.policy.NetworkController_dual@42947c08)

mWifiVisible          : Some(true)

mWifiStrengthId       : Some(id: 2130837963 name: stat_sys_wifi_signal_2)

mMobileVisible        : Some(true)

mMobileVisible2       : Some(false)

mMobileStrengthId1    : Some(id: 2130837914 name: stat_sys_signal_4)

mMobileStrengthId2    : Some(unknown id: 0)

mMobileActivityId1    : Some(unknown id: 0)

mMobileActivityId2    : Some(unknown id: 0)

mMobileTypeId1        : Some(unknown id: 0)

mMobileTypeId2        : Some(unknown id: 0)

mIsAirplaneMode       : Some(false)

mAirplaneIconId       : Some(unknown id: 0)

mHasService           : Some(false)

mSimIconVisible       : Some(true)

mSimIconId            : Some(id: 2130837705 name: stat_sim_gsm_1)

mMobileRoamingId      : Some(unknown id: 0)

mMobileRoamingId2     : Some(unknown id: 0)

mMobileRssiId         : Some(unknown id: 0)

mMobileRssiId2        : Some(unknown id: 0)

mMobileDataState      : Some(-1)

mMobileDataState2     : Some(0)

fsbi >> dual >> data vis: Some(true) | Some(false) lvl: Some(Some(100)) | Some(None) tpe: Some(None) | Some(None)
fsbi >> dual >> SignalClusterView

mNC                   : Some(com.android.systemui.statusbar.policy.NetworkController_dual@42947c08)

mWifiVisible          : Some(true)

mWifiStrengthId       : Some(id: 2130837963 name: stat_sys_wifi_signal_2)

mMobileVisible        : Some(

**Comment by abdujack** [comment]
Update: i can see the download button using version 1.4.1 but it says download failed.
Here a log when i used the version..

**Comment by abdujack** [comment]
sbi >> dual >> SignalClusterView

mNC                   : Some(com.android.systemui.statusbar.policy.NetworkController_dual@42a5c968)

mWifiVisible          : Some(true)

mWifiStrengthId       : Some(id: 2130837963 name: stat_sys_wifi_signal_2)

mMobileVisible        : Some(true)

mMobileVisible2       : Some(false)

mMobileStrengthId1    : Some(id: 2130837914 name: stat_sys_signal_4)

mMobileStrengthId2    : Some(unknown id: 0)

mMobileActivityId1    : Some(unknown id: 0)

mMobileActivityId2    : Some(unknown id: 0)

mMobileTypeId1        : Some(id: 2130837745 name: stat_sys_data_connected_3g)

mMobileTypeId2        : Some(unknown id: 0)

mIsAirplaneMode       : Some(false)

mAirplaneIconId       : Some(unknown id: 0)

mHasService           : Some(false)

mSimIconVisible       : Some(true)

mSimIconId            : Some(id: 2130837705 name: stat_sim_gsm_1)

mMobileRoamingId      : Some(unknown id: 0)

mMobileRoamingId2     : Some(unknown id: 0)

mMobileRssiId         : Some(unknown id: 0)

mMobileRssiId2        : Some(unknown id: 0)

mMobileDataState      : Some(-1)

mMobileDataState2     : Some(0)

fsbi >> dual >> data vis: Some(true) | Some(false) lvl: Some(Some(100)) | Some(None) tpe: Some(Some(3G)) | Some(None)
java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.TypedArray to class android.content.res.XResources$XTypedArray
	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:773)
	at de.robv.android.xposed.XposedBridge.access$6(XposedBridge.java:759)
	at de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:358)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.content.res.TypedArray.<init>(Native Method)
	at android.content.res.Resources.getCachedStyledAttributes(Resources.java:3790)
	at android.content.res.Resources.access$400(Resources.java:109)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java:2571)
	at android.content.Context.obtainStyledAttributes(Context.java:439)
	at android.view.View.<init>(View.java:3538)
	at android.view.ViewGroup.<init>(ViewGroup.java:470)
	at android.widget.FrameLayout.<init>(FrameLayout.java:101)
	at android.widget.FrameLayout.<init>(FrameLayout.java:97)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:601)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:676)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:701)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.widget.RemoteViews.apply(RemoteViews.java:2916)
	at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:903)
	at com.android.systemui.statusbar.BaseStatusBar.createNotificationViews(BaseStatusBar.java:1155)
	at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1484)
	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:407)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5590)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.TypedArray to class android.content.res.XResources$XTypedArray
	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:773)
	at de.robv.android.xposed.XposedBridge.access$6(XposedBridge.java:759)
	at de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:358)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.content.res.TypedArray.<init>(Native Method)
	at android.content.res.Resources.getCachedStyledAttributes(Resources.java:3790)
	at android.content.res.Resources.obtainAttributes(Resources.java:2696)
	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:117)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:973)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
	at android.content.res.Resources.loadDrawable(Resources.java:3449)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:614)
	at android.view.View.<init>(View.java:3585)
	at android.view.ViewGroup.<init>(ViewGroup.java:470)
	at android.widget.FrameLayout.<init>(FrameLayout.java:101)
	at android.widget.FrameLayout.<init>(FrameLayout.java:97)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:601)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:676)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:701)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.widget.RemoteViews.apply(RemoteViews.java:2916)
	at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:903)
	at com.android.systemui.statusbar.BaseStatusBar.createNotificationViews(BaseStatusBar.java:1155)
	at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1484)
	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:407)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5590)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
java.lang.IllegalArgumentException: Cannot transfer object from class android.content.res.TypedArray to class android.content.res.XResources$XTypedArray
	at de.robv.android.xposed.XposedBridge.setObjectClass(XposedBridge.java:773)
	at de.robv.android.xposed.XposedBridge.access$6(XposedBridge.java:759)
	at de.robv.android.xposed.XposedBridge$7.afterHookedMethod(XposedBridge.java:358)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.content.res.TypedArray.<init>(Native Method)
	at android.content.res.Resources.getCachedStyledAttributes(Resources.java:3790)
	at android.content.res.Resources.obtainAttributes(Resources.java:2696)
	at android.graphics.drawable.Drawable.inflate(Drawable.java:1009)
	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:113)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:973)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
	at android.content.res.Resources.loadDrawable(Resources.java:3449)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:614)
	at android.widget.ProgressBar.<init>(ProgressBar.java:283)
	at android.widget.ProgressBar.<init>(ProgressBar.java:267)
	at android.widget.ProgressBar.<init>(ProgressBar.java:263)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:601)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:676)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:701)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:762)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:771)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.widget.RemoteViews.apply(RemoteViews.java:2916)
	at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:903)
	at com.android.systemui.statusbar.BaseStatusBar.createNotificationViews(BaseStatusBar.java:1155)
	at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1484)
	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:407)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5590)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
fsbi >> icon >> ctrl >> mapping >> notification_eslogo (2130838031;com.estrongs.android.pop.pro) >> None
fsbi >> icon >> ctrl >> * SET >> Notification >> 0.75 >> true, _, 2130838031, com.estrongs.android.pop.pro, notification_eslogo
fsbi >> notifications >> all: 4 > visible: 5 > custom: 1 > hidden: 0
fsbi >> icon >> ctrl >> mapping >> notification_copy (2130838028;com.estrongs.android.pop.pro) >> None
fsbi >> icon >> ctrl >> * SET >> Notification >> 0.75 >> true, _, 2130838028, com.estrongs.android.pop.pro, notification_copy
fsbi >> notifications >> all: 5 > visible: 5 > custom: 1 > hidden: 0
fsbi >> icon >> ctrl >> * SET >> Notification >> 0.65000004 >> true, _, 2130838028, com.estrongs.android.pop.pro, notification_copy
fsbi >> dual >> SignalClusterView

mNC                   : Some(com.android.systemui.statusbar.policy.NetworkController_dual@42a5c968)

mWifiVisible          : Some(true)

mWifiStrengthId       : Some(id: 2130837963 name: stat_sys_wifi_signal_2)

mMobileVisible        : Some(true)

mMobileVisible2       : Some(false)

mMobileStrengthId1    : Some(id: 2130837914 name: stat_sys_signal_4)

mMobileStrengthId2    : Some(unknown id: 0)

mMobileActivityId1    : Some(unknown id: 0)

mMobileActivityId2    : Some(unknown id: 0)

mMobileTypeId1        : Some(id: 2130837745 name: stat_sys_data_connected_3g)

mMobileTypeId2        : Some(unknown id: 0)

mIsAirplaneMode       : Some(false)

mAirplaneIconId       : Some(unknown id: 0)

mHasService           : Some(false)

mSimIconVisible       : Some(true)

mSimIconId            : Some(id: 2130837705 name: stat_sim_gsm_1)

mMobileRoamingId      : Some(unknown id: 0)

mMobileRoamingId2     : Some(unknown id: 0)

mMobileRssiId         : Some(unknown id: 0)

mMobileRssiId2        : Some(unknown id: 0)

mMobileDataState      : Some(-1)

mMobileDataState2     : Some(0)

fsbi >> dual >> data vis: Some(true) | Some(false) lvl: Some(Some(100)) | Some(None) tpe: Some(Some(3G)) | Some(None)

**Comment by skyguy126** [comment]
I don't see anything regarding scd in there. The log should look something like this

```
02-25 14:12:20.547 I/Xposed  ( 3227): [SoundCloud Downloader] Module entry, version 1.5.1
02-25 14:12:20.583 I/Xposed  ( 3227): [SoundCloud Downloader] Initialized
02-25 14:13:08.322 I/XposedInstaller( 5202): Downloaded http://dl.xposed.info/repo/partial/14328.xml.gz with status 0 (error: null), size 32031 bytes
02-25 14:13:08.541 I/XposedInstaller( 5202): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 14348 (12 new / 0 removed modules)
02-25 14:13:14.815 I/Xposed  ( 5398): [SoundCloud Downloader] Module entry, version 1.5.1
02-25 14:13:14.828 I/Xposed  ( 5398): [SoundCloud Downloader] Initialized
02-25 14:13:27.829 I/Xposed  ( 5828): YouTube: com.google.android.apps.youtube.gaming 2.06.36.1 loaded with module version 4.3.2
02-25 14:13:35.899 I/Xposed  ( 6200): YouTube: com.google.android.youtube 13.06.53 loaded with module version 4.3.2
02-25 14:13:50.440 I/Xposed  ( 5398): [SoundCloud Downloader] Entered download catcher...
02-25 14:13:50.445 I/Xposed  ( 5398): [SoundCloud Downloader] Track name: [REDACTED]
02-25 14:13:50.445 I/Xposed  ( 5398): [SoundCloud Downloader] Image url: [REDACTED]
02-25 14:13:50.451 I/Xposed  ( 5398): [SoundCloud Downloader] com.skyguy126.soundclouddownloader scd_prefs
02-25 14:13:50.454 I/Xposed  ( 5398): [SoundCloud Downloader] Include metadata: true
02-25 14:13:50.454 I/Xposed  ( 5398): [SoundCloud Downloader] Save location: 2
```

Edit: Can you try and paste the log file in a text-file github seems to have a character limit.

**Comment by skyguy126** [comment]
If it's just an installation issue, try uninstalling scd, full rebooting, installing it again, enable do a full reboot again.

**Comment by abdujack** [comment]
Okay.. I tried and did not succeed, I think the issue is in my phone..
Although other modules work well.

**Comment by skyguy126** [comment]
Refer to #15; there has been an update and module hooks need to be updated. What version of soundcloud are you running?

**Comment by abdujack** [comment]
My phone is Samsung galaxy J1ace SM-J110H Android Kitkat 4.4.4

**Comment by abdujack** [comment]
Soundcloud 2017.12.18

**Comment by skyguy126** [comment]
This module is for version **2018.02.14**. I'm not sure if an earlier version will work with your current version, maybe try looking around in the releases section. Adding backwards compatibility would make the module take much longer to update unfortunately. Sorry

**Comment by abdujack** [comment]
I'll try use version 2018.02.14
Thank you anyway 💛
